name: Deploy-Hexo to Github pages
on:
  push:
   branches:
    - master # master 分支
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false # 下载子模块
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Node.js 版本
      - name: Install Dependencies
        run: npm install

      - name: Install Hexo Git Deployer
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-cli -g
      - name: clean and Generate Static Files
        run: |
          hexo clean
          hexo generate
      - name: Configure Git
        run: |
          git config --global user.name "MegumiN152"
          git config --global user.email "3105755134@qq.com"
      - name: Deploy to Github Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd public/
          git init
          git add -A
          git commit -m "Create by workflow"
          git remote  add origin https://$GH_TOKEN@github.com/MegumiN152/hexo-blog-hh.git
          git push  origin HEAD:ph-pages -f